### ISSUE TITLE
Κατηγορία - Κόστος Εναρξης

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#10]
UI/UX design για το κόστος έναρξης. Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1. Επιλογή απάντησης από drop down
2. Συμπλήρωση κενών
3. Button υπολογισμού συνολικού κόστους
4. Δημιουργία αντίγραφου των components (εικονίδιο προσθήκης)
