### ISSUE TITLE
Κατηγορία - Κόστος Λειτουργίας

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#11]
UI/UX design για το κόστος λειτουργίας. Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1.Συμπλήρωση κενών
2.Button υπολογισμού συνολικού κόστους
3.Δημιουργία αντίγραφου των components (εικονίδιο προσθήκης)
