### ISSUE TITLE
Testing - Synopsis

### ISSUE THREAD

**Issue by gassio** [eellak/business-plan-tool#112]

**Comment by KonstantinosNikopoulos** [comment]
Οι οδηγίες λειτουργούν κανονικά και είναι κατατοπιστικές.
![11](https://user-images.githubusercontent.com/35402328/36073090-9fca9146-0f33-11e8-8413-029c3c35468f.png)

Το πεδίο "Σύνοψη του επιχειρηματικού σχεδίου" λειτουργεί και μπορεί να συμπληρωθεί.
![12](https://user-images.githubusercontent.com/35402328/36073144-601ebfbc-0f34-11e8-8d68-e2ad273a2197.png)
