### ISSUE TITLE
Κατηγορία - Ανάλυση Νεκρού Σημείου

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#12]
UI/UX design για τη σελίδα ανάλυσης νεκρού σημείου. Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1.Συμπλήρωση κενών
2.Button υπολογισμού νεκρού σημείου
3.Δημιουργία αντίγραφου των components (εικονίδιο προσθήκης)
