### ISSUE TITLE
Testing - 10 Export pdf

### ISSUE THREAD

**Issue by gassio** [eellak/business-plan-tool#130]

**Comment by MargaritaSar** [comment]
Κάνοντας κλικ στο κουμπί "Export" , δημιουργείται με σωστό και αναμενόμενο τρόπο το pdf αρχείο που περιέχει αναλυτικά και με την καθορισμένη σειρά το επιχειρηματικό σχέδιο που έχει φτιάξει ο χρήστης.

**Comment by MargaritaSar** [comment]
Μια προεπισκόπηση της πρώτης σελίδας του αρχείου.

![screenshot 2018-01-24 19 47 25](https://user-images.githubusercontent.com/34173213/35347999-6ff929d4-013f-11e8-8e8d-55061a98cf74.png)
