### ISSUE TITLE
Κατηγορία - Ανάλυση SWOT

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#15]
UI/UX design για την ανάλυση SWOT. 
Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις  
1. Συμπλήρωση κενών (4 απαιτούμενα πεδία)
2. Προσθήκη επιπρόσθετων κενών (εικονίδιο προσθήκης)
