### ISSUE TITLE
Testing database REST API calls

### ISSUE THREAD

**Issue by gassio** [eellak/business-plan-tool#152]
@tsampazk Please test the GET, POST, PUT, DELETE call of the new database url in order to see if the desired results are coming.
http://play-trinity.com/theo/bplantool/api/'resource-name'

- [x] Identity
- [x] Client
- [x] IdentityClient
- [x] Description

- [x] Manager

- [x] Employee

- [x] Partner

- [x] EmployeeSalary

- [x] Faculty

- [x] Equipment

- [x] RunningCost

- [x] Product

- [x] SWOT

- [x] Factor

- [x] Note

- [x] Strategy

- [x] MarketingAction

- [x] StartAction

- [x] FunctionCost

- [x] Deadspot

- [x] Link

- [x] Conclusion

- [x] Typos

**Comment by tsampazk** [comment]
Client PUT returning correct response with edited data. Then GET returns object as it was before PUT.

DELETE works correctly

**Comment by tsampazk** [comment]
Client:
POST creates a new element correctly. 
DELETE works correctly.
PUT returns correct, edited data, but then GET returns old data as if it wasn't edited. PUT not working?

**Comment by venetheo** [comment]
issue with clients resource on PUT resolved

**Comment by tsampazk** [comment]
Manager:
PUT returning null

**Comment by tsampazk** [comment]
Partner:
POST returns "ID": 0 instead of assigned ID
PUT returns null

**Comment by tsampazk** [comment]
EmployeeSalary:
POST returns null, no object added
PUT works correctly, editing data, but returns sent ID instead of proper assigned ID as in other resources

**Comment by venetheo** [comment]
Fixed :
-Manager PUT
-Partner POST response ID
-Partner PUT
-EmployeeSalary PUT response ID

EmployeeSalary POST references employees on primary key employeeID and therefore you cannot add more than one salaries for a single employee (one to one connection between tables)

**Comment by venetheo** [comment]
Fixed :
-Manager PUT
-Partner POST response ID
-Partner PUT
-EmployeeSalary PUT response ID

EmployeeSalary POST references employees on primary key employeeID and therefore you cannot add more than one salaries for a single employee (one to one connection between tables)

**Comment by tsampazk** [comment]
Product:
POST returns null, nothing added
PUT returns null, nothing edited
DELETE ok

**Comment by tsampazk** [comment]
Factor: 
-POST returns sent ID instead of assigned ID
-POST does not assign correct ID, instead assigns whatever ID was sent.
-PUT requires sending correct ID to work, if no ID or wrong ID is sent it returns null
-DELETE does not work, returns null (worked only when the element with ID:3 was sent and deleted it correctly)

**Comment by tsampazk** [comment]
Note:
-POST does not work, returns null
-PUT edits the text field, but cannot change the businessPlanID (intended because of how the db works?)
-DELETE works

**Comment by tsampazk** [comment]
Strategy:
One Strategy per business plan? POST does not work. 
How to reference a strategy, based on businessPlanId inside the JSON, or the number at the end of the URL? 
Had some weird behaviour in PUT, with the URL ending in 3 but the businessPlanId = 2. It edited the fields of the businessPlanId =2

**Comment by tsampazk** [comment]
MarketingAction:
POST, PUT, DELETE working as expected.
totalCost field is a String?

**Comment by tsampazk** [comment]
Deadspot:
-POST does not work, returns null, even if existing productID/businessPlanId are given
-PUT, DELETE same as in Strategy, how to reference them?

**Comment by tsampazk** [comment]
Conclusion:
typo "BussinesPlanId" -> "BusinessPlanId"

**Comment by tsampazk** [comment]
FacultyCost:
POST creates faculty cost correctly for existing faculty.
PUT returns sent ID instead of correct ID (?) and does not edit the item. 
PUT: to work it requires correct ID both in the URL and the sent JSON. If intended, disregard.
DELETE works as expected.

**Comment by venetheo** [comment]
Product : fixed POST,PUT
Factor : Has a different logic as requested from the front-end where id references business plan id and post requires both ids
Note : each business plan has 1 note ,so no more notes are allowed on POST for each business plan and therefore it can't be changed on PUT
Strategy : Each business plan has 1 strategy and therefore id references business plan id,fixed PUT
MarketingAction : changed totalCost to int
Deadspot: now has DeadspotID and can be referenced directly
Typos : changed Adress to Address and BussinesPlanId to BusinessPlanId ,the rest are not needed
FacultyCost : fixed PUT 
EquipmentCost : fixed PUT

**Comment by tsampazk** [comment]
@venetheo  Thank you, all issues fixed or disregarded as intended.

**Comment by tsampazk** [comment]
Partner From-Until dates in PUT: 
Until goes into From and From goes into Until

**Comment by venetheo** [comment]
Should be ok now
