### ISSUE TITLE
Κατηγορία - Ανάλυση PESTEL

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#16]
UI/UX design για την ανάλυση PESTEL.
Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1. Ανάπτυξη κενών για 12 υποχρεωτικά πεδία ( ανάλυση 6 παραγόντων με περιγραφή και παραδείγματα)
