### ISSUE TITLE
Κατηγορία - Προιόντα και Υπηρεσίες

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#18]
UI/UX design για την καταγραφή προιόντων & υπηρεσιών.
Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1. Συμπλήρωση κενών 
2. Επιλογή απάντησης από drop down
3. Επιλογή απάντησης τύπου checkbox
4. Χρήση συνδέσμου μεταξύ ενότητας και αρχείων τύπου πιστοποιητικών εγγράφων.
5. Προσθήκη αντίγραφου των προαναφερόμενων components (εικονίδιο προσθήκης)
