### ISSUE TITLE
Κατηγορία - Πνευματική Ιδιοκτησία

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#19]
UI/UX design για την κατοχύρωση πνευματικής ιδιοκτησίας των προιόντων-υπηρεσιών της επιχείρησης. 
Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1. Επιλογή απάντησης από drop down
2. Προσθήκη αντίγραφου των components (εικονίδιο προσθήκης)
