### ISSUE TITLE
Κατηγορία - Ανάλυση Εσόδων

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#20]
UI/UX design για την ανάλυση εσόδων. 
Υλοποίηση σε Adobe Photoshop.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1. Συμπλήρωση κενών με αριθμητικούς χαρακτήρες
2. Προσθήκη αντιγράφου των component (εικονίδιο προσθήκης)
