### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by gassio** [eellak/business-plan-tool#200]

**Comment by gassio** [comment]
https://i.pinimg.com/564x/b2/73/ca/b273ca5e55b173ec42ae6e32eb52698f.jpg

**Comment by kellyMalerou** [comment]
![welcome page - bp tool](https://user-images.githubusercontent.com/35432179/40611195-0546c3f8-627e-11e8-9e25-97bb2f2b903d.jpg)
