### ISSUE TITLE
Κατηγορία - Τόπος Εγκατάστασης

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#25]
UI/UX design για τον τόπο εγκατάστασης.
Υλοποίηση σε Adobe Photoshop.

Ο χρήστης εισάγει για κάθε κτιριακή εγκατάσταση τα απαραίτητα στοιχεία στα ανάλογα πεδία.
Για κάθε εγκατάσταση επιλέγει το checkbox ΧΡΗΣΗ ΑΠΟ ΤΗΝ ΕΝΑΡΞΗ αν η εγκατάσταση θα χρησιμοποιείται (και επομένως θα κοστίζει χρήματα στην επιχείρηση) από την έναρξή της.

**Comment by gassio** [comment]
![4-1 topos egatastasis](https://user-images.githubusercontent.com/9654021/34447986-1d31b9b6-ecf2-11e7-9f59-a9d8d5a20e50.png)

**Comment by DemonFurby** [comment]
![4-1 topos egatastasis](https://user-images.githubusercontent.com/10411265/34448303-b1285da8-ecf4-11e7-9073-d478614d12fb.png)
