### ISSUE TITLE
Prototype στο invision

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#3]
Υλοποίηση prototype που θα συνδέει τις επιμέρους οθόνες (columns 1-10)
Προσθήκη διαδραστικότητας για οπτικοποίηση των μενού, της βοήθειας και της πλοήγησης μεταξύ των ενοτήτων.

**Comment by Kostis-S-Z** [comment]
https://projects.invisionapp.com/share/P2F44NDD8
