### ISSUE TITLE
Design System for HTML/CSS

### ISSUE THREAD

**Issue by danaepolychron** [eellak/business-plan-tool#37]
Create a Design System to facilitate HTML and CSS coding

**Comment by danaepolychron** [comment]
[Fonts - Colors - Icons.docx](https://github.com/eellak/business-plan-tool/files/1599612/Fonts.-.Colors.-.Icons.docx)

**Comment by Kostis-S-Z** [comment]
Ειναι ακομα ανοιχτο issue αυτο?
