### ISSUE TITLE
Κατηγορία - Παράρτημα

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#4]
UI/UX για την ενότητα του Παραρτήματος

Δυνατότητα του χρήστη να προσθέτει αρχεία (upload), να βλέπει λεπτομέρειες για τα ανεβασμένα αρχεία και να εμφανίζει τα αρχεία.

**Comment by danaepolychron** [comment]
Απαιτήσεις ¨
1.Παρουσίαση αρχείων με χαρακτηριστικά (εικονίδιο, όνομα, ώρα δημιουργίας, σύνδεσμος, επιπλέον πληροφορίες
2.Δυνατότητα προσθήκης αρχείου (εικονίδιο προσθήκης ή/και πλαίσιο drag and drop)
