### ISSUE TITLE
Κατηγορία - Xρονοδιάγραμμα GANNT

### ISSUE THREAD

**Issue by DemonFurby** [eellak/business-plan-tool#5]
UI/UX για την ενότητα χρονοδιαγράμματος. Yλοποίηση σε Adobe Photoshop.

Ο χρήστης θα έχει τη δυνατότητα να παραμετροποιήσει διαδραστικά ένα gannt διάγραμμα.

**Comment by danaepolychron** [comment]
Απαιτήσεις
1. Χρήση βιβλιοθήκης frappe gantt
2. Filtering στο χρονοδιάγραμμα
